name: Dev.to

on: 
  push:

env:
 token: ${{ secrets.DEV_TOKEN }}
 
jobs:
  post:
    runs-on: ubuntu-latest
    name: Post to Dev
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: echo ${{ github }}
#       - name: Write Post
#         id: write
#         uses: ./.github/actions/dev
