name: Dev.to

on: 
  push:

env:
 token: ${{ secrets.DEV_TOKEN }}
 
jobs:
  post:
    runs-on: ubuntu-latest
    name: Post to Dev
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          npm uninstall node-fetch
          npm install axios
      - name: Write Post
        id: write
        uses: ./.github/actions/dev
